apiVersion: v1
kind: Template
metadata:
  name: hotrod
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: example-hotrod
    name: example-hotrod
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: example-hotrod
      deploymentconfig: example-hotrod
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: example-hotrod
          deploymentconfig: example-hotrod
      spec:
        containers:
        - image: jaegertracing/example-hotrod:1.6
          imagePullPolicy: IfNotPresent
          name: example-hotrod
          ports:
          - containerPort: 8083
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          - containerPort: 8082
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - command:
          - /go/bin/agent-linux
          - --collector.host-port=jaeger-collector.jaeger-test.svc:14267
          image: jaegertracing/jaeger-agent
          imagePullPolicy: Always
          name: jaeger-agent
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 5778
            protocol: TCP
          - containerPort: 6831
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - example-hotrod
        from:
          kind: ImageStreamTag
          name: example-hotrod:1.6
          namespace: jaeger-test
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: example-hotrod
    name: example-hotrod
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: 8082-tcp
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: 8083-tcp
      port: 8083
      protocol: TCP
      targetPort: 8083
    selector:
      app: example-hotrod
      deploymentconfig: example-hotrod
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: example-hotrod
    name: example-hotrod
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: example-hotrod
      weight: 100
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow
