apiVersion: v1
kind: Template
metadata:
  name: demo-squash
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      app: example-service1
    name: example-service1-1
  spec:
    replicas: 1
    selector:
      app: example-service1
      deployment: example-service1-1
      deploymentconfig: example-service1
    template:
      metadata:
        labels:
          app: example-service1
          deployment: example-service1-1
          deploymentconfig: example-service1
      spec:
        containers:
        - image: quay.io/dwojciec/example-service1:v0.2.2
          imagePullPolicy: IfNotPresent
          name: example-service1
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      app: example-service2
      openshift.io/deployment-config.name: example-service2
    name: example-service2-1
  spec:
    replicas: 1
    selector:
      app: example-service2
      deployment: example-service2-1
      deploymentconfig: example-service2
    template:
      metadata:
        labels:
          app: example-service2
          deployment: example-service2-1
          deploymentconfig: example-service2
      spec:
        containers:
        - image: quay.io/dwojciec/example-service2:v0.2.2
          imagePullPolicy: IfNotPresent
          name: example-service2
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: example-service1
    name: example-service1
  spec:
    ports:
    - name: 8080-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: example-service1
      deploymentconfig: example-service1
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: example-service2
    name: example-service2
  spec:
    ports:
    - name: 8080-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: example-service2
      deploymentconfig: example-service2
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 5m
      openshift.io/host.generated: "true"
    labels:
      app: example-service1
    name: example-service1
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: example-service1
      weight: 100
    wildcardPolicy: None
